# Generated by Django 2.1.3 on 2018-12-08 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabasePurger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('delete_by_age', models.BooleanField(default=True, help_text='Delete if entry is older than specified age')),
                ('delete_by_quantity', models.BooleanField(default=False, help_text='Delete all except the youngest `max_records` entries')),
                ('datetime_field', models.CharField(default='created', max_length=255)),
                ('age_in_days', models.PositiveIntegerField(default=30)),
                ('max_records', models.PositiveIntegerField(default=1000, help_text='Number of records to keep if `delete_by_quantity` is selected')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('hour', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23')], default=0)),
                ('day', models.IntegerField(choices=[(-1, '*'), (0, 'Su'), (1, 'M'), (2, 'Tu'), (3, 'W'), (4, 'Th'), (5, 'F'), (6, 'Sa')], default=-1)),
            ],
        ),
    ]
