language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - pip install pylint

script:
  - coverage run manage.py test
  - pylint purge

after_success:
  coveralls
