# Generated by Django 2.1.3 on 2019-04-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_purge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePurger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('file_pattern', models.CharField(help_text="Pattern of files to inspect using POSIX shell expansion (e.g., 'datafile-.*\\\\.txt')", max_length=255)),
                ('directory', models.CharField(blank=True, max_length=255)),
                ('recursive_search', models.BooleanField(default=False, help_text='Search directories recursively')),
                ('age_in_days', models.PositiveIntegerField(default=30, help_text='Delete records older than this age')),
                ('delete_by_filename', models.BooleanField(blank=True, default=True, help_text='Delete by timestamp in filename')),
                ('filename_date_year_first', models.BooleanField(default=False, help_text='Whether we should expect the year to come first')),
                ('filename_date_day_first', models.BooleanField(default=False, help_text='Whether we should expect the day to come before the month')),
                ('delete_by_atime', models.BooleanField(default=False, help_text='Delete if access time is too old')),
                ('delete_by_mtime', models.BooleanField(default=True, help_text='Delete if modification time is too old')),
                ('delete_by_ctime', models.BooleanField(default=False, help_text='Delete if (meta) change time is too old')),
            ],
            options={
                'verbose_name': 'File Purger',
            },
        ),
        migrations.AlterField(
            model_name='databasepurger',
            name='datetime_field',
            field=models.CharField(default='created', help_text='Date or datetime field used to determine the age of a record', max_length=255),
        ),
    ]
