# Generated by Django 2.1.3 on 2019-05-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_purge', '0002_auto_20190402_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databasepurger',
            options={},
        ),
        migrations.AlterModelOptions(
            name='filepurger',
            options={},
        ),
    ]
