# Generated by Django 2.1.3 on 2019-05-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_purge', '0003_auto_20190509_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepurger',
            name='file_pattern',
            field=models.CharField(help_text="Pattern of files to inspect using POSIX shell expansion (e.g., 'datafile-.*\\.txt')", max_length=255),
        ),
    ]
